### ISSUE TITLE
All controller methods should have the consumes/produces values specified

### ISSUE THREAD

**Issue by ivuorio** [three-consulting/epoc-backend#46]
Not an issue for this pr but since the GET is allowed to consume all values, the POST/PUT should be limited to APPLICATION_JSON or whatever it is. Similarly all controller methods should have the consumes/produces values specified. Just a thought.

_Originally posted by @LeadingMoominExpert in https://github.com/three-consulting/epoc-backend/pull/44#discussion_r715445343_

**Comment by LeadingMoominExpert** [comment]
e.g.
```kotlin
import org.springframework.http.MediaType.APPLICATION_JSON_VALUE
...
@PostMapping(consumes = [APPLICATION_JSON_VALUE], produces = [APPLICATION_JSON_VALUE])
```
on https://github.com/three-consulting/epoc-backend/blob/main/src/main/kotlin/three/consulting/epoc/controller/CustomerController.kt#L16

Delete method only consumes json, doesn't produce anything. Controller methods without any request body consume ALL_VALUE
